### ISSUE TITLE
Ketiv/Qere

### ISSUE THREAD

**Issue by jcuenod** [codykingham/tischendorf_tf#1]
Why the names "Ketiv" and "Qere"? (I haven't looked at the Tisch data in ages but I'm not sure what this means outside of a MT context)

**Comment by codykingham** [comment]
Hi @jcuenod ,

Here is the explanation from Ulrik:

> As of version 2.0 of the text, there is an extra field in the
database, namely the "qere" for each word.  In Hebrew Masoretic texts,
there is a distinction between the "Kethiv" (that which is written)
and the "Qere" (that which should be read).  This distinction is
present in versions 2.0 and above of this database.  The Kethiv is
that which is written in the printed Tischendorf.  The Qere is what
the editor thinks it should have been.
> Most often, this amounts to differences in accentuation or diacritics.
In a few cases, it amounts to a change in the word itself (e.g.,
Revelation 14:18, where the printed text reads TOI\S BO/TRUAS, where
this editor thinks it should have been TOU\S BO/TRUAS, on account of
the grammar).
> For the vast majority of words, the Qere is identical to the Kethiv.
> The parsing always follows the Qere, not the Kethiv.

See the explanation in context [here](https://github.com/morphgnt/tischendorf-data/tree/master/word-per-line/2.8).

I will be adding a feature explanation to the /docs/feature.md in order to clarify these kinds of questions in the future.
